#!/usr/bin/env bun
/*
 * Build-time script that scans every plate YAML for the line number of each
 * known top-level section key, then writes the mapping to
 * src/generated/peptide-lines.ts.
 *
 * The mapping powers GitHub deep-links from each plate section's pencil
 * affordance (SectionFrame component): the URL points at the YAML file +
 * #L<line>, opening the editor at the right place. Lines drift as
 * contributions add or remove text above the section — we accept ~5-line
 * drift per D10. Worst case the editor opens off by a few lines.
 *
 * The output file is gitignored. Wired into predev/prebuild/pretest/prelint
 * so it is regenerated on every command path that touches it.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const PEPTIDES_DIR = join(REPO_ROOT, "content", "peptides");
const OUTPUT_FILE = join(REPO_ROOT, "src", "generated", "peptide-lines.ts");

const SECTION_KEYS = [
  "mechanism",
  "dosage",
  "reconstitution",
  "evidence",
  "side_effects",
  "administration",
  "synergy",
  "sources",
] as const;

type SectionKey = (typeof SECTION_KEYS)[number];

const files = readdirSync(PEPTIDES_DIR).filter(
  (f) => f.endsWith(".yaml") && f !== "_template.yaml",
);

const result: Record<string, Partial<Record<SectionKey, number>>> = {};
const errors: string[] = [];

for (const file of files) {
  const path = join(PEPTIDES_DIR, file);
  const raw = readFileSync(path, "utf8");

  try {
    yaml.load(raw);
  } catch (err) {
    errors.push(`${file}: ${(err as Error).message}`);
    continue;
  }

  const slug = file.replace(/\.yaml$/, "");
  const lines = raw.split("\n");
  const sections: Partial<Record<SectionKey, number>> = {};

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    for (const key of SECTION_KEYS) {
      if (line.startsWith(`${key}:`) && !(key in sections)) {
        sections[key] = i + 1;
      }
    }
  }

  result[slug] = sections;
}

if (errors.length > 0) {
  console.error("[yaml-line-map] FAIL: malformed YAML files:");
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}

mkdirSync(dirname(OUTPUT_FILE), { recursive: true });

const sortedSlugs = Object.keys(result).sort();
const out: string[] = [];
out.push(`// AUTO-GENERATED by scripts/yaml-line-map.ts — do not edit by hand.`);
out.push(`// Regenerate with: bun run build:line-map`);
out.push(`// This file is gitignored; CI regenerates it fresh on each run.`);
out.push(``);
out.push(`export type SectionKey =`);
for (let i = 0; i < SECTION_KEYS.length; i++) {
  const key = SECTION_KEYS[i];
  const sep = i === SECTION_KEYS.length - 1 ? ";" : "";
  out.push(`  | "${key}"${sep}`);
}
out.push(``);
out.push(
  `export const PEPTIDE_LINES: Record<string, Partial<Record<SectionKey, number>>> = {`,
);
for (const slug of sortedSlugs) {
  const sections = result[slug];
  const entries = Object.entries(sections)
    .map(([k, v]) => `${k}: ${v}`)
    .join(", ");
  out.push(`  "${slug}": { ${entries} },`);
}
out.push(`};`);
out.push(``);

writeFileSync(OUTPUT_FILE, out.join("\n"));

const totalSections = Object.values(result).reduce(
  (sum, s) => sum + Object.keys(s).length,
  0,
);
console.log(
  `[yaml-line-map] OK: ${files.length} peptides, ${totalSections} sections mapped → ${relative(REPO_ROOT, OUTPUT_FILE)}`,
);
